import { Router } from "express";
import pkgRoutes from "./package.routes.js";
import authRouter from "./auth.routes.js";
import categoryRoute from "./category.routes.js";
import bookingRoutes from "./booking.routes.js";
import destinationRoutes from "./destination.routes.js";
import paymentRoute from "./payment.routes.js";
import blogRoutes from "./blog.routes.js";
import uploadRoutes from "./upload.routes.js";
import authorRoutes from "./author.routes.js";
import contactRoute from "./contact.routes.js";
import commentRoutes from "./comment.routes.js";
import newsRoutes from "./news.routes.js";
import newsCommentRoutes from "./newsComment.js";
import footerRoutes from "./footer.routes.js";
import itineraryRoutes from "./itinerary.routes.js";
import visaRoutes from "./visa.routes.js";
import webPageRoute from "./webPage.routes.js";
import membershipRoutes from "./membership.routes.js";
import membershipBookingRoute from "./membershipBooking.routes.js";
import counterRoutes from "./counter.routes.js";
const router = Router();

router.use("/packages", pkgRoutes);
router.use("/auth", authRouter);
router.use("/category", categoryRoute);
router.use("/booking", bookingRoutes);
router.use("/destination", destinationRoutes);
router.use("/payment", paymentRoute);
router.use("/blogs", blogRoutes);
router.use("/upload", uploadRoutes);
router.use("/authors", authorRoutes);
router.use("/contact", contactRoute);
router.use("/comments", commentRoutes);
router.use("/news", newsRoutes);
router.use("/newscomments", newsCommentRoutes);
router.use("/footer", footerRoutes);
router.use("/itinerary", itineraryRoutes);
router.use("/visa", visaRoutes);
router.use("/webpage", webPageRoute);
router.use("/membership", membershipRoutes);
router.use("/membershipbooking", membershipBookingRoute);
router.use("/counter", counterRoutes);
export default router;
