import { Router } from "express";
import pkgRoutes from "./package.routes.js";
import authRouter from "./auth.routes.js";
import staffRouter from "./staff.routes.js";
import categoryRoute from "./category.routes.js";
import bookingRoutes from "./booking.routes.js";
import destinationRoutes from "./destination.routes.js";
import paymentRoute from "./payment.routes.js";
import blogRoutes from "./blog.routes.js";
import uploadRoutes from "./upload.routes.js";
import authorRoutes from "./author.routes.js";
import contactRoute from "./contact.routes.js";
import commentRoutes from "./comment.routes.js";
import newsRoutes from "./news.routes.js";
import newsCommentRoutes from "./newsComment.js";
import footerRoutes from "./footer.routes.js";
import itineraryRoutes from "./itinerary.routes.js";
import visaRoutes from "./visa.routes.js";
import webPageRoute from "./webPage.routes.js";
import membershipRoutes from "./membership.routes.js";
import membershipBookingRoute from "./membershipBooking.routes.js";
import counterRoutes from "./counter.routes.js";
import jobRoute from "./job.routes.js";
import jobApplicationRoutes from "./jobApplication.routes.js";
import aboutUsRoutes from "./aboutUs.routes.js";
import customizedPackageRoutes from "./customizedPackage.routes.js";
import customizedBookingRoutes from "./customizedBooking.routes.js";
import customizedTourPackageRoute from "./customizedTourPackage.route.js";
import customizedTourBookingRoute from "./customizedTourBooking.routes.js";
import batchRoutes from "./batch.routes.js";
import dashboardRoute from "./dashboard.routes.js";
import destinationSeoRoute from "./destinationSeo.routes.js";
import mediaRoutes from "./media.routes.js";
import reviewRoutes from "./reviews.routes.js";
import videoBannerRoutes from "./videoBanner.routes.js";
import otpRoutes from "./enquiryOtp.routes.js";
import documentRoutes from "./document.routes.js";
import coupanRoutes from "./coupan.routes.js";
import newsletterRoutes from "./newsletter.routes.js";
import popupRoutes from "./popup.routes.js";
import vehicleRoutes from "./vehicle.routes.js";
import vehicleBookingsRoutes from "./vehicleBooking.routes.js";

const router = Router();

router.use("/packages", pkgRoutes);
router.use("/auth", authRouter);
router.use("/admin", staffRouter);
router.use("/category", categoryRoute);
router.use("/booking", bookingRoutes);
router.use("/destination", destinationRoutes);
router.use("/payment", paymentRoute);
router.use("/blogs", blogRoutes);
router.use("/upload", uploadRoutes);
router.use("/authors", authorRoutes);
router.use("/contact", contactRoute);
router.use("/comments", commentRoutes);
router.use("/news", newsRoutes);
router.use("/newscomments", newsCommentRoutes);
router.use("/footer", footerRoutes);
router.use("/itinerary", itineraryRoutes);
router.use("/visa", visaRoutes);
router.use("/webpage", webPageRoute);
router.use("/membership", membershipRoutes);
router.use("/membershipbooking", membershipBookingRoute);
router.use("/counter", counterRoutes);
router.use("/job", jobRoute);
router.use("/jobapplication", jobApplicationRoutes);
router.use("/aboutus", aboutUsRoutes);
router.use("/customizedpackage", customizedPackageRoutes);
router.use("/customizedbooking", customizedBookingRoutes);
router.use("/customizedtourpackage", customizedTourPackageRoute);
router.use("/customizedtourbooking", customizedTourBookingRoute);
router.use("/batch", batchRoutes);
router.use("/dashboard", dashboardRoute);
router.use("/destinationseo", destinationSeoRoute);
router.use("/media", mediaRoutes);
router.use("/reviews", reviewRoutes);
router.use("/videobanner", videoBannerRoutes);
router.use("/enquiry-otp", otpRoutes);
router.use("/document", documentRoutes);
router.use("/coupan", coupanRoutes);
router.use("/newsletter", newsletterRoutes);
router.use("/popup", popupRoutes);
router.use("/vehicle", vehicleRoutes);
router.use("/vehicle-booking", vehicleBookingsRoutes);
export default router;
